# Site settings
title: granthutchison.com
email: grant@granthutchison.com
description: > # this means to ignore newlines until "baseurl:"
  <strong>Grant Hutchison</strong> is a professional software tester, and has over a decades experience working in the UK financial services industry. Outside of work he enjoys studying with the Open University, playing board games and tinkering with code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.granthutchison.com" # the base hostname & protocol for your site
twitter_username: Stif_br0
google_plus_username: +GrantHutchison
github_username:  Stif-UK
linkedin_profile: https://uk.linkedin.com/pub/grant-hutchison/34/614/437


# Build settings
markdown: kramdown

host: 0.0.0.0
port: 4000

