# Site settings
title: granthutchison.com
email: grant.jh.hutchison@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Stif_br0
google_plus_username: +GrantHutchison
github_username:  Stif-UK
linkedin_profile: https://uk.linkedin.com/pub/grant-hutchison/34/614/437


# Build settings
markdown: kramdown

host: 0.0.0.0
port: 4000

